# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
configfile: "config/config.yaml"
# Include the wrangling rules
include: "wrangling.smk"

rule all:
    input:
        expand("1kdown/{population_id}.vcf.gz", population_id=config["populations"])

# Other global rules, configurations, or includes


